version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

# finally, we can define the initialization server
# this runs the `rs.initiate` command to intialize
# the replica set and connect the three servers to each other
  # mongoinit:
  #   image: mongo
  #   # this container will exit after executing the command
  #   restart: "no"
  #   depends_on:
  #     - mongo1
  #   command: >
  #     mongo --host mongo1:27017 --eval 
  #     '
  #     db = (new Mongo("localhost:27017")).getDB("test");
  #     config = {
  #     "_id" : "my-mongo-set",
  #     "members" : [
  #       {
  #         "_id" : 0,
  #         "host" : "mongo1:27017"
  #       },
  #       {
  #         "_id" : 1,
  #         "host" : "mongo2:27017"
  #       },
  #       {
  #         "_id" : 2,
  #         "host" : "mongo3:27017"
  #       }
  #     ]
  #     };
  #     rs.initiate(config);
  #     '  