version: '3'

services:
  auctionserver:
    #build: 
    #  context: .
    image: 127.0.0.1:5000/auctionrest
    container_name: auctionrest
    ports:
      - 3000:3000
    # deploy:
    #   mode: replicated
    #   replicas: 3
    #   labels:
    #     description: "auction rest services"
    environment:
      - PORT=3000
      - ADDRESS=192.168.18.221
      - DB_CONNECTION=mongodb://192.168.18.221:27018/aunt-rich
      - DATABASE_USER=root
      - DATABASE_PASS=lol123
    # links:
    #   - redis
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379